### ISSUE TITLE
Send headers

### ISSUE THREAD

**Issue by thureos** [Codeception/codeception.github.com#156]
Hello, 

So I need to send headers to my app but neither of these won't work:
```yaml
class_name: ApiTester
modules:
    enabled:
        - Helper\Api
        - Asserts
        - REST:
            depends: Laravel5
            headers:
                header_1: value_1
        - Laravel5:
            environment_file: .env.dev
            cleanup: false # This removes the transaction error when running
            url: http://localhost
            # run_database_migrations: true
            # run_database_seeder: true
            # database_seeder_class: 'DatabaseSeeder'
```

```yaml
class_name: ApiTester
modules:
    enabled:
        - Helper\Api
        - Asserts
        - REST:
            depends: Laravel5
        - Laravel5:
            depends: PhpBrowser
            environment_file: .env.dev
            cleanup: false # This removes the transaction error when running
            url: http://localhost
            # run_database_migrations: true
            # run_database_seeder: true
            # database_seeder_class: 'DatabaseSeeder'
        - PhpBrowser:
            url: http://localhost
            headers:
                header1: value_1
```

and Laravel5 does not appear to have a header option

Thanks,
